---
output:md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Data Dictionary##



####CSV files####

1) andre-iguodala.csv
2) draymond-green.csv
3) kevin-durant.csv
4) klay-thompson.csv
5) stephen-curry.csv

####Vairables with descriptions####

1) team_name: team name

2) game_date: game date

3) season: season

4) period: an NBA game is divided in 4 periods of 12 mins each. For example, a value for period = 1 refers to the first period (the first 12 mins of the game)

5) minutes_remaining: minutes remained to be played in a given period

6) seconds_remaining: seconds remained to be played in a given period

7) shot_made_flag: whether a shot was made (y) or missed (n)

8) action_type: has to do with the basketball moves used by players, either to pass by defenders to gain access to the basket, or to get a clean pass to a teammate to score a two pointer or three pointer

9) shot_type: indicates whether a shot is a 2-point field goal, or a 3-point field goal

10) shot_distance: distance to the basket (measured in feet)

11) opponent: the other team

12) x: the court coordinates (measured in inches) where a shot occurred

13) y: the court coordinates (measured in inches) where a shot occurred

